# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this f>
# reopened with the relevant failures.
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadat>
  creationTimestamp: "2026-03-23T22:10:23Z"
  generation: 2
  labels:
    release: kube-prometheus-stack
  name: nanogpt-monitor
  namespace: default
  resourceVersion: "10236"
  uid: 48435f6c-b232-448d-bb76-edebd0e81077
spec:
  endpoints:
  - interval: 5s
    port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: nanogpt
