apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanogpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanogpt
  template:
    metadata:
      labels:
        app: nanogpt
    spec:
      containers:
        - name: nanogpt
          image: nanogpt:latest
          imagePullPolicy: Never   # <-- Add this line
          ports:
            - containerPort: 8000
            - containerPort: 8001